name: Dependabot auto-merge

on: pull_request_target

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    uses: ryansonshine/ryansonshine/.github/workflows/automerge.yml@main
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
